# Generated by Django 5.1.1 on 2024-09-09 21:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('sex', models.CharField(max_length=50, verbose_name='Sexo')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telephone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo electrónico')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('history_medical_number', models.CharField(max_length=10, verbose_name='Número de historia clinica')),
                ('last_eye_exam', models.DateField(verbose_name='Ultimo examen de la vista')),
                ('frame_only', models.BooleanField(default=False, verbose_name='Compra solo armazón')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Departamento de producto',
                'verbose_name_plural': 'Departamentos de productos',
                'db_table': 'departamento_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('sex', models.CharField(max_length=50, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Salario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d', verbose_name='Avatar')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d', verbose_name='Currículum')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EyesGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_eye', models.CharField(choices=[('derecho', 'Derecho'), ('izquierdo', 'Izquierdo'), ('ambos', 'Ambos')], max_length=50, verbose_name='Ojo a graduar')),
                ('sph', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Esfera')),
                ('cyl', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cilindro')),
                ('axis', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eje')),
                ('ao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura de oblea')),
                ('add', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Adición')),
                ('prism', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prisma')),
                ('base', models.CharField(blank=True, max_length=50, null=True, verbose_name='Base')),
                ('observation', models.TextField(max_length=200, verbose_name='Observación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Graduación de ojos',
                'verbose_name_plural': 'Graduaciones de ojos',
                'db_table': 'graduacion_ojos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HeadOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telephone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='CEO')),
            ],
            options={
                'verbose_name': 'Sucursal Matriz',
                'verbose_name_plural': 'Sucursales Matrices',
                'db_table': 'sucursal_matriz',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telephone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('branch_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Gerente de sucursal')),
                ('head_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.headoffice', verbose_name='Sucursal matriz')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departament', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'puesto',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.jobs', verbose_name='Puesto'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Clave')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('price_purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra')),
                ('stock', models.IntegerField(default=0, verbose_name='Existencia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Impuestos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoría')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departamentproduct', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de cotización')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.branchoffice', verbose_name='Sucursal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Producto')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
                'db_table': 'detalle_cotizacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de venta')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto pagado')),
                ('credit', models.BooleanField(default=False, verbose_name='Crédito')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto de crédito')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Límite de crédito')),
                ('credit_days', models.IntegerField(default=0, verbose_name='Días de crédito')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.branchoffice', verbose_name='Sucursal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'detalle_venta',
                'ordering': ['id'],
            },
        ),
    ]
